package main

import (
	"github.com/aws-opsworks-cm/mcp-server/config"
	"github.com/aws-opsworks-cm/mcp-server/models"
	tools_x_amz_target_opsworkscm_v2016_11_01_deletebackup "github.com/aws-opsworks-cm/mcp-server/tools/x_amz_target_opsworkscm_v2016_11_01_deletebackup"
	tools_x_amz_target_opsworkscm_v2016_11_01_associatenode "github.com/aws-opsworks-cm/mcp-server/tools/x_amz_target_opsworkscm_v2016_11_01_associatenode"
	tools_x_amz_target_opsworkscm_v2016_11_01_describenodeassociationstatus "github.com/aws-opsworks-cm/mcp-server/tools/x_amz_target_opsworkscm_v2016_11_01_describenodeassociationstatus"
	tools_x_amz_target_opsworkscm_v2016_11_01_createbackup "github.com/aws-opsworks-cm/mcp-server/tools/x_amz_target_opsworkscm_v2016_11_01_createbackup"
	tools_x_amz_target_opsworkscm_v2016_11_01_createserver "github.com/aws-opsworks-cm/mcp-server/tools/x_amz_target_opsworkscm_v2016_11_01_createserver"
	tools_x_amz_target_opsworkscm_v2016_11_01_deleteserver "github.com/aws-opsworks-cm/mcp-server/tools/x_amz_target_opsworkscm_v2016_11_01_deleteserver"
	tools_x_amz_target_opsworkscm_v2016_11_01_describeevents "github.com/aws-opsworks-cm/mcp-server/tools/x_amz_target_opsworkscm_v2016_11_01_describeevents"
	tools_x_amz_target_opsworkscm_v2016_11_01_untagresource "github.com/aws-opsworks-cm/mcp-server/tools/x_amz_target_opsworkscm_v2016_11_01_untagresource"
	tools_x_amz_target_opsworkscm_v2016_11_01_updateserverengineattributes "github.com/aws-opsworks-cm/mcp-server/tools/x_amz_target_opsworkscm_v2016_11_01_updateserverengineattributes"
	tools_x_amz_target_opsworkscm_v2016_11_01_restoreserver "github.com/aws-opsworks-cm/mcp-server/tools/x_amz_target_opsworkscm_v2016_11_01_restoreserver"
	tools_x_amz_target_opsworkscm_v2016_11_01_describebackups "github.com/aws-opsworks-cm/mcp-server/tools/x_amz_target_opsworkscm_v2016_11_01_describebackups"
	tools_x_amz_target_opsworkscm_v2016_11_01_exportserverengineattribute "github.com/aws-opsworks-cm/mcp-server/tools/x_amz_target_opsworkscm_v2016_11_01_exportserverengineattribute"
	tools_x_amz_target_opsworkscm_v2016_11_01_describeaccountattributes "github.com/aws-opsworks-cm/mcp-server/tools/x_amz_target_opsworkscm_v2016_11_01_describeaccountattributes"
	tools_x_amz_target_opsworkscm_v2016_11_01_listtagsforresource "github.com/aws-opsworks-cm/mcp-server/tools/x_amz_target_opsworkscm_v2016_11_01_listtagsforresource"
	tools_x_amz_target_opsworkscm_v2016_11_01_startmaintenance "github.com/aws-opsworks-cm/mcp-server/tools/x_amz_target_opsworkscm_v2016_11_01_startmaintenance"
	tools_x_amz_target_opsworkscm_v2016_11_01_describeservers "github.com/aws-opsworks-cm/mcp-server/tools/x_amz_target_opsworkscm_v2016_11_01_describeservers"
	tools_x_amz_target_opsworkscm_v2016_11_01_tagresource "github.com/aws-opsworks-cm/mcp-server/tools/x_amz_target_opsworkscm_v2016_11_01_tagresource"
	tools_x_amz_target_opsworkscm_v2016_11_01_disassociatenode "github.com/aws-opsworks-cm/mcp-server/tools/x_amz_target_opsworkscm_v2016_11_01_disassociatenode"
	tools_x_amz_target_opsworkscm_v2016_11_01_updateserver "github.com/aws-opsworks-cm/mcp-server/tools/x_amz_target_opsworkscm_v2016_11_01_updateserver"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_x_amz_target_opsworkscm_v2016_11_01_deletebackup.CreateDeletebackupTool(cfg),
		tools_x_amz_target_opsworkscm_v2016_11_01_associatenode.CreateAssociatenodeTool(cfg),
		tools_x_amz_target_opsworkscm_v2016_11_01_describenodeassociationstatus.CreateDescribenodeassociationstatusTool(cfg),
		tools_x_amz_target_opsworkscm_v2016_11_01_createbackup.CreateCreatebackupTool(cfg),
		tools_x_amz_target_opsworkscm_v2016_11_01_createserver.CreateCreateserverTool(cfg),
		tools_x_amz_target_opsworkscm_v2016_11_01_deleteserver.CreateDeleteserverTool(cfg),
		tools_x_amz_target_opsworkscm_v2016_11_01_describeevents.CreateDescribeeventsTool(cfg),
		tools_x_amz_target_opsworkscm_v2016_11_01_untagresource.CreateUntagresourceTool(cfg),
		tools_x_amz_target_opsworkscm_v2016_11_01_updateserverengineattributes.CreateUpdateserverengineattributesTool(cfg),
		tools_x_amz_target_opsworkscm_v2016_11_01_restoreserver.CreateRestoreserverTool(cfg),
		tools_x_amz_target_opsworkscm_v2016_11_01_describebackups.CreateDescribebackupsTool(cfg),
		tools_x_amz_target_opsworkscm_v2016_11_01_exportserverengineattribute.CreateExportserverengineattributeTool(cfg),
		tools_x_amz_target_opsworkscm_v2016_11_01_describeaccountattributes.CreateDescribeaccountattributesTool(cfg),
		tools_x_amz_target_opsworkscm_v2016_11_01_listtagsforresource.CreateListtagsforresourceTool(cfg),
		tools_x_amz_target_opsworkscm_v2016_11_01_startmaintenance.CreateStartmaintenanceTool(cfg),
		tools_x_amz_target_opsworkscm_v2016_11_01_describeservers.CreateDescribeserversTool(cfg),
		tools_x_amz_target_opsworkscm_v2016_11_01_tagresource.CreateTagresourceTool(cfg),
		tools_x_amz_target_opsworkscm_v2016_11_01_disassociatenode.CreateDisassociatenodeTool(cfg),
		tools_x_amz_target_opsworkscm_v2016_11_01_updateserver.CreateUpdateserverTool(cfg),
	}
}
